{% set name = "tom-tns" %}
{% set version = "0.4.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tom_tns-{{ version }}.tar.gz
  sha256: b828546c20a3b294d4f7f23ea2c51d26e74f734e71300f501d064ef2e81658e0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=2.0,<3.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - python >={{ python_min }}
    - tomtoolkit >=2.20.0,<3

test:
  imports:
    - tom_tns
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/TOMToolkit/tom_tns
  summary: TOMtoolkit module for reporting transients to the TNS
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - miguelgomezgomez
    - davner
    - phycodurus
    - jchate6
