{% set name = "tom-tns" %}
{% set version = "0.3.5" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tom_tns-{{ version }}.tar.gz
  sha256: a0802e46029268c6b940377bb7935888b81ffe764c0a1cd0a50619396181fa55

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=2.0,<3.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - python >={{ python_min }}
    - tomtoolkit >=2.20.0,<3

test:
  imports:
    - tom_tns
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/TOMToolkit/tom_tns
  summary: TOMtoolkit module for reporting transients to the TNS
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - davner
    - phycodurus
    - jchate6
